# Generated by Django 4.2.11 on 2024-04-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arrendatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("celular", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Casillero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10, unique=True)),
                ("ubicacion", models.CharField(max_length=100)),
                ("ocupado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("pagado", models.BooleanField(default=False)),
                (
                    "arrendatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="casilleros.arrendatario",
                    ),
                ),
                (
                    "casillero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="casilleros.casillero",
                    ),
                ),
            ],
        ),
    ]
